@host = http://localhost:5242

POST {{host}}/auth/registro
content-type: application/json;

{
    "nombre": "Usuario",
    "apellido": "Test",
    "email": "usuario.test@gmail.com",
    "password": "usaurio.test1234$"
}