@host = http://localhost:5242

POST {{host}}/auth/registro
content-type: application/json;

{
    "nombre": "",
    "apellido": "",
    "email": "usuario.test@gmail.com",
    "password": "usaurio.test1234$"
}